[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [
    { access = "read", path = "./out"},
    { access = "read", path = "./node_modules/@uniswap"}
]